name = "get-content" 
main = "index.js"
node_compat = true
compatibility_date = "2022-05-03"

[vars]
GOOGLE_SHEETS_SERVICE_ACCOUNT = "athkar@athkar-449114.iam.gserviceaccount.com"
GOOGLE_SHEETS_ID = "1GdrHtnI3a_QGolXyr2T5ehOqwQvnUQjQ4wbtAK-xHxQ"
GOOGLE_SHEETS_PAGE = "0"